2016-05-28 09:44:31|582 [main] INFO  com.test.Application.logStarting:48 -
                Starting Application v0.1.0 on elsanli-PC2 with PID 18128 (E:\workSpace\gaia-stack-0516-ok-1\target\test-0.1.0.jar started by elsanli in E:\workSpace\gaia-stack-0516-ok-1\target)
2016-05-28 09:44:31|593 [main] INFO  com.test.Application.logStartupProfileInfo:666 -
                No active profile set, falling back to default profiles: default
2016-05-28 09:44:31|728 [main] INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext.prepareRefresh:578 -
                Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@55b78c89: startup date [Sat May 28 09:44:31 GMT+08:00 2016]; root of context hierarchy
2016-05-28 09:44:34|003 [main] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition:839 -
                Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2016-05-28 09:44:34|895 [main] INFO  org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.<init>:153 -
                JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-05-28 09:44:35|062 [main] INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker.postProcessAfterInitialization:328 -
                Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$22780380] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-05-28 09:44:36|048 [main] INFO  org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize:81 -
                Tomcat initialized with port(s): 8798 (http)
2016-05-28 09:44:36|078 [main] INFO  org.apache.catalina.core.StandardService.log:180 -
                Starting service Tomcat
2016-05-28 09:44:36|079 [main] INFO  org.apache.catalina.core.StandardEngine.log:180 -
                Starting Servlet Engine: Apache Tomcat/8.0.30
2016-05-28 09:44:36|375 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:180 -
                Initializing Spring embedded WebApplicationContext
2016-05-28 09:44:36|375 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader.prepareEmbeddedWebApplicationContext:272 -
                Root WebApplicationContext: initialization completed in 4647 ms
2016-05-28 09:44:37|155 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.ServletRegistrationBean.onStartup:189 -
                Mapping servlet: 'dispatcherServlet' to [/]
2016-05-28 09:44:37|166 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'metricFilter' to: [/*]
2016-05-28 09:44:37|167 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'characterEncodingFilter' to: [/*]
2016-05-28 09:44:37|168 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-05-28 09:44:37|169 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-05-28 09:44:37|169 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'requestContextFilter' to: [/*]
2016-05-28 09:44:37|169 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'webRequestLoggingFilter' to: [/*]
2016-05-28 09:44:37|170 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.FilterRegistrationBean.configure:258 -
                Mapping filter: 'applicationContextIdFilter' to: [/*]
2016-05-28 09:44:37|758 [main] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory:339 -
                Building JPA container EntityManagerFactory for persistence unit 'default'
2016-05-28 09:44:40|469 [main] ERROR org.apache.tomcat.jdbc.pool.ConnectionPool.log:182 -
                Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:124) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1887) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1845) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at com.test.Application.main(Application.java:20) [test-0.1.0.jar!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [test-0.1.0.jar!/:0.1.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_77]
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_77]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	... 60 common frames omitted
2016-05-28 09:44:40|902 [main] ERROR org.apache.tomcat.jdbc.pool.ConnectionPool.log:182 -
                Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126) [tomcat-jdbc-8.0.30.jar!/:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:219) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:203) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:522) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at com.test.Application.main(Application.java:20) [test-0.1.0.jar!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [test-0.1.0.jar!/:0.1.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_77]
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_77]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	... 58 common frames omitted
2016-05-28 09:44:40|951 [main] ERROR org.hibernate.tool.hbm2ddl.SchemaUpdate.execute:226 -
                HHH000319: Could not get database metadata
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:219) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:203) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:522) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at com.test.Application.main(Application.java:20) [test-0.1.0.jar!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [test-0.1.0.jar!/:0.1.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_77]
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_77]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	... 58 common frames omitted
2016-05-28 09:44:41|072 [main] ERROR org.hibernate.tool.hbm2ddl.SchemaUpdate.execute:272 -
                HHH000299: Could not complete schema update
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:981) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2253) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2286) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126) ~[tomcat-jdbc-8.0.30.jar!/:na]
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:51) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:219) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:203) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:522) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425) [hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849) [hibernate-entitymanager-4.3.11.Final.jar!/:4.3.11.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318) [spring-orm-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.2.RELEASE.jar!/:1.3.2.RELEASE]
	at com.test.Application.main(Application.java:20) [test-0.1.0.jar!/:0.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54) [test-0.1.0.jar!/:0.1.0]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_77]
Caused by: java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_77]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_77]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_77]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_77]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298) ~[mysql-connector-java-5.1.38.jar!/:5.1.38]
	... 58 common frames omitted
2016-05-28 09:44:41|917 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.initControllerAdviceCache:532 -
                Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@55b78c89: startup date [Sat May 28 09:44:31 GMT+08:00 2016]; root of context hierarchy
2016-05-28 09:44:42|164 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.register:527 -
                Mapped "{[/v2*/test/imagelist],methods=[GET]}" onto public java.lang.String com.test.api.registry.TestController.test()
2016-05-28 09:44:42|171 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.register:527 -
                Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-05-28 09:44:42|173 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.register:527 -
                Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-05-28 09:44:42|251 [main] INFO  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping.registerHandler:341 -
                Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-05-28 09:44:42|252 [main] INFO  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping.registerHandler:341 -
                Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-05-28 09:44:42|356 [main] INFO  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping.registerHandler:341 -
                Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-05-28 09:44:43|491 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.afterSingletonsInstantiated:431 -
                Registering beans for JMX exposure on startup
2016-05-28 09:44:43|499 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.afterSingletonsInstantiated:431 -
                Registering beans for JMX exposure on startup
2016-05-28 09:44:43|503 [main] INFO  org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext.prepareRefresh:578 -
                Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@428595b3: startup date [Sat May 28 09:44:43 GMT+08:00 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@55b78c89
2016-05-28 09:44:43|584 [main] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition:839 -
                Overriding bean definition for bean 'handlerExceptionResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration; factoryMethodName=handlerExceptionResolver; initMethodName=null; destroyMethodName=(inferred); defined in class org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=endpointWebMvcChildContextConfiguration; factoryMethodName=compositeHandlerExceptionResolver; initMethodName=null; destroyMethodName=(inferred); defined in org.springframework.boot.actuate.autoconfigure.EndpointWebMvcChildContextConfiguration]
2016-05-28 09:44:43|636 [main] INFO  org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.<init>:153 -
                JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-05-28 09:44:43|667 [main] INFO  org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize:81 -
                Tomcat initialized with port(s): 8797 (http)
2016-05-28 09:44:43|668 [main] INFO  org.apache.catalina.core.StandardService.log:180 -
                Starting service Tomcat
2016-05-28 09:44:43|669 [main] INFO  org.apache.catalina.core.StandardEngine.log:180 -
                Starting Servlet Engine: Apache Tomcat/8.0.30
2016-05-28 09:44:43|680 [localhost-startStop-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat-1].[localhost].[/].log:180 -
                Initializing Spring embedded WebApplicationContext
2016-05-28 09:44:43|681 [localhost-startStop-1] INFO  org.springframework.web.context.ContextLoader.prepareEmbeddedWebApplicationContext:272 -
                Root WebApplicationContext: initialization completed in 178 ms
2016-05-28 09:44:43|685 [localhost-startStop-1] INFO  org.springframework.boot.context.embedded.ServletRegistrationBean.onStartup:189 -
                Mapping servlet: 'dispatcherServlet' to [/]
2016-05-28 09:44:43|812 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/dump || /dump.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|813 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/beans || /beans.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|814 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/trace || /trace.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|814 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/autoconfig || /autoconfig.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|818 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/configprops || /configprops.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|821 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/env/{name:.*}],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EnvironmentMvcEndpoint.value(java.lang.String)
2016-05-28 09:44:43|821 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/env || /env.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|823 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/health || /health.json],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.HealthMvcEndpoint.invoke(java.security.Principal)
2016-05-28 09:44:43|823 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/info || /info.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|824 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/mappings || /mappings.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|825 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/metrics/{name:.*}],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.MetricsMvcEndpoint.value(java.lang.String)
2016-05-28 09:44:43|826 [main] INFO  org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping.register:527 -
                Mapped "{[/metrics || /metrics.json],methods=[GET],produces=[application/json]}" onto public java.lang.Object org.springframework.boot.actuate.endpoint.mvc.EndpointMvcAdapter.invoke()
2016-05-28 09:44:43|856 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.register:527 -
                Mapped "{[/error]}" onto public java.util.Map<java.lang.String, java.lang.Object> org.springframework.boot.actuate.endpoint.mvc.ManagementErrorEndpoint.invoke()
2016-05-28 09:44:43|867 [main] INFO  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping.registerHandler:341 -
                Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-05-28 09:44:43|868 [main] INFO  org.springframework.web.servlet.handler.SimpleUrlHandlerMapping.registerHandler:341 -
                Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-05-28 09:44:43|890 [main] INFO  org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.initControllerAdviceCache:532 -
                Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@428595b3: startup date [Sat May 28 09:44:43 GMT+08:00 2016]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@55b78c89
2016-05-28 09:44:43|994 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log:180 -
                Initializing ProtocolHandler ["http-nio-0.0.0.0-8797"]
2016-05-28 09:44:44|014 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log:180 -
                Starting ProtocolHandler ["http-nio-0.0.0.0-8797"]
2016-05-28 09:44:44|081 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool.log:180 -
                Using a shared selector for servlet write/read
2016-05-28 09:44:44|147 [main] INFO  org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start:162 -
                Tomcat started on port(s): 8797 (http)
2016-05-28 09:44:44|159 [main] INFO  org.springframework.context.support.DefaultLifecycleProcessor.start:341 -
                Starting beans in phase 0
2016-05-28 09:44:44|164 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'requestMappingEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=requestMappingEndpoint]
2016-05-28 09:44:44|229 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'environmentEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=environmentEndpoint]
2016-05-28 09:44:44|239 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'healthEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=healthEndpoint]
2016-05-28 09:44:44|243 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'beansEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=beansEndpoint]
2016-05-28 09:44:44|247 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'infoEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=infoEndpoint]
2016-05-28 09:44:44|251 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'metricsEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=metricsEndpoint]
2016-05-28 09:44:44|255 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'traceEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=traceEndpoint]
2016-05-28 09:44:44|259 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'dumpEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=dumpEndpoint]
2016-05-28 09:44:44|270 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'autoConfigurationReportEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=autoConfigurationReportEndpoint]
2016-05-28 09:44:44|275 [main] INFO  org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter.registerBeanInstance:674 -
                Located managed bean 'configurationPropertiesReportEndpoint': registering with JMX server as MBean [org.springframework.boot:type=Endpoint,name=configurationPropertiesReportEndpoint]
2016-05-28 09:44:44|300 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log:180 -
                Initializing ProtocolHandler ["http-nio-8798"]
2016-05-28 09:44:44|301 [main] INFO  org.apache.coyote.http11.Http11NioProtocol.log:180 -
                Starting ProtocolHandler ["http-nio-8798"]
2016-05-28 09:44:44|309 [main] INFO  org.apache.tomcat.util.net.NioSelectorPool.log:180 -
                Using a shared selector for servlet write/read
2016-05-28 09:44:44|324 [main] INFO  org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start:162 -
                Tomcat started on port(s): 8798 (http)
2016-05-28 09:44:44|329 [main] INFO  com.test.Application.logStarted:57 -
                Started Application in 13.5 seconds (JVM running for 21.236)
2016-05-28 09:45:37|506 [http-nio-8798-exec-1] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].log:180 -
                Initializing Spring FrameworkServlet 'dispatcherServlet'
2016-05-28 09:45:37|506 [http-nio-8798-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet.initServletBean:489 -
                FrameworkServlet 'dispatcherServlet': initialization started
2016-05-28 09:45:37|540 [http-nio-8798-exec-1] INFO  org.springframework.web.servlet.DispatcherServlet.initServletBean:508 -
                FrameworkServlet 'dispatcherServlet': initialization completed in 34 ms
2016-05-28 09:45:37|833 [http-nio-8798-exec-1] INFO  com.test.api.registry.TestController.test:22 -
                Get images for project {} 
2016-05-28 09:45:42|249 [http-nio-8798-exec-3] INFO  com.test.api.registry.TestController.test:22 -
                Get images for project {} 
2016-05-28 09:45:48|450 [http-nio-8798-exec-5] INFO  com.test.api.registry.TestController.test:22 -
                Get images for project {} 
2016-05-28 09:47:33|963 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:47:33|963 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:47:33|974 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:47:33|974 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:47:33|976 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:47:33|976 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:50:19|035 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:50:19|035 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:50:19|046 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:50:19|046 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:50:19|048 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:50:19|049 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:53:04|162 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:53:04|162 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:53:04|173 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:53:04|173 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:53:04|185 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:53:04|185 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:55:49|232 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:55:49|235 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:55:49|238 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:55:49|239 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:55:49|251 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:55:49|251 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:58:34|385 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:58:34|385 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:58:34|386 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:58:34|387 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 09:58:34|398 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 09:58:34|398 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:01:19|441 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:01:19|442 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:01:19|454 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:01:19|455 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:01:19|457 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:01:19|457 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:04:04|593 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:04:04|593 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:04:04|604 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:04:04|604 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:04:04|615 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:04:04|615 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:06:49|686 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:06:49|686 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:06:49|698 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:06:49|698 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:06:49|710 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:06:49|710 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:09:34|884 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:09:34|885 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:09:34|897 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:09:34|897 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:09:34|909 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:09:34|910 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:12:20|014 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:12:20|015 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:12:20|028 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:12:20|029 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:12:20|040 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:12:20|040 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:15:05|203 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:15:05|203 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:15:05|215 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:15:05|215 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:15:05|227 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:15:05|227 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:17:50|303 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:17:50|304 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:17:50|307 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:17:50|308 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:17:50|310 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:17:50|311 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:20:35|466 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:20:35|467 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:20:35|469 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:20:35|469 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:20:35|472 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:20:35|473 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:23:20|520 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:23:20|520 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:23:20|532 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:23:20|533 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:23:20|544 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:23:20|544 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:24:55|414 [http-nio-8798-exec-7] INFO  com.test.api.registry.TestController.test:22 -
                Get images for project {} 
2016-05-28 10:26:05|664 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:26:05|664 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:26:05|675 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:26:05|675 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:26:05|686 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:26:05|686 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:28:50|751 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:28:50|751 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:28:50|762 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:28:50|762 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:28:50|773 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:28:50|773 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:31:35|917 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:31:35|917 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:31:35|928 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:31:35|928 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:31:35|929 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:31:35|929 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:34:20|972 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:34:20|972 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:34:20|983 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:34:20|983 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:34:20|994 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:34:20|994 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:37:06|160 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:37:06|160 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:37:06|171 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:37:06|171 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:37:06|172 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:37:06|172 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:39:51|244 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:39:51|244 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:39:51|245 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:39:51|245 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:39:51|246 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:39:51|246 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:42:36|338 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:42:36|338 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:42:36|339 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:42:36|340 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:42:36|340 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:42:36|341 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:45:21|390 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:45:21|390 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:45:21|391 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:45:21|391 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:45:21|402 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:45:21|402 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:48:06|512 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:48:06|512 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:48:06|523 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:48:06|523 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:48:06|534 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:48:06|534 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:50:51|598 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:50:51|600 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:50:51|611 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:50:51|612 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:50:51|623 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:50:51|623 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:53:36|749 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:53:36|750 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:53:36|761 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:53:36|762 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:53:36|776 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:53:36|777 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:56:21|836 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:56:21|836 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:56:21|847 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:56:21|847 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:56:21|858 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:56:21|858 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:59:06|999 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:59:06|999 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:59:07|001 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:59:07|002 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 10:59:07|013 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 10:59:07|013 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:01:52|078 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:01:52|078 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:01:52|090 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:01:52|090 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:01:52|092 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:01:52|092 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:04:37|237 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:04:37|238 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:04:37|249 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:04:37|251 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:04:37|264 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:04:37|264 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:07:22|323 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:07:22|323 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:07:22|334 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:07:22|334 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:07:22|335 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:07:22|336 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:10:07|416 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:10:07|416 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:10:07|417 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:10:07|418 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:10:07|430 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:10:07|430 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:12:52|476 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:12:52|476 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:12:52|487 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:12:52|487 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:12:52|488 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:12:52|488 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:15:37|644 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:15:37|644 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:15:37|645 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:15:37|645 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:15:37|656 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:15:37|656 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:18:22|734 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:18:22|734 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:18:22|735 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:18:22|735 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:18:22|746 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:18:22|746 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:21:07|831 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:21:07|832 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:21:07|833 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:21:07|833 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:21:07|844 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:21:07|844 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:23:52|899 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:23:52|899 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:23:52|910 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:23:52|910 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:23:52|921 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:23:52|921 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:26:38|023 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:26:38|024 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:26:38|034 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:26:38|034 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:26:38|045 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:26:38|045 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:29:23|088 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:29:23|088 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:29:23|099 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:29:23|099 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:29:23|100 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:29:23|101 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:32:08|213 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:32:08|213 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:32:08|224 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:32:08|224 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:32:08|235 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:32:08|235 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:34:53|298 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:34:53|298 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:34:53|309 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:34:53|309 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:34:53|320 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:34:53|320 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:37:38|454 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:37:38|454 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:37:38|465 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:37:38|465 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
2016-05-28 11:37:38|476 [New Relic Utilization Service] INFO  global.log:87 -
                I/O exception (java.net.SocketException) caught when processing request: Network is unreachable: connect
2016-05-28 11:37:38|476 [New Relic Utilization Service] INFO  global.log:87 -
                Retrying request
